### ISSUE TITLE
Semi-automatic image rotation or image sorting

### ISSUE THREAD

**Issue by Burt360** [haltosan/RA-python-tools#4]
I found this [stackoverflow question](https://stackoverflow.com/questions/69818302/how-to-automatically-rotate-images-based-on-text). It suggests some ideas to speed up image rotation.

I think one way to develop it would be to present some large thumbnails of images (like 12), and we/rapid response could click images to rotate them
- left click: counterclockwise
- right click: clockwise
- middle/wheel click: rotate 180 degrees
- space bar: next set of images.

Thoughts? I'm not really sure where this is with regard to the project's needs... or if there's already another method under development...
I'd be down to try working on this.

**Comment by Burt360** [comment]
I wonder if a similar method could speed up the image sorting if that's still in progress (like present a thumbnail and someone types three characters for the last name, then show the next image and the program would put the image in the right spot)...

**Comment by haltosan** [comment]
I like the semi-automatic method. Sadly, there are way too many so we need an automatic method. I found some methods, and all have failed for one reason or another (EXIF data isn't always present or accurate, certain methods only rotate a few degrees, etc.). This is a great strategy to fall back on, but for now we should shoot for automation.

**Comment by haltosan** [comment]
I have something working fairly well right now. It's the file at V:\papers\current\tree_growth\US\Skagit\skagit_obits\4_Image_Flipping\flippy-4.py
The only images it doesn't seem to work really well on are the upside down images. I feel this isn't a large amount of images, so we can always run it as is.

**Comment by Burt360** [comment]
@haltosan Ok neat. What about the image sorting alphabetically? Is that being done entirely manually? It seems like that would take even longer than image rotating... Could the final CSV file that has the last names be used to put the images into corresponding folders? It looks the original image name is recorded
